### ISSUE TITLE
Why the images use <a href="#">?

### ISSUE THREAD

**Issue by yyuna** [emotionLoop/visualCaptcha-frontend-angular#8]
a href="#" go to the state '' when I use angular-ui-router.
It(href="#") seems to be unnecessary, and brings some problems.

**Comment by BrunoBernardino** [comment]
Hi @yyuna. It's because of accessibility: https://github.com/emotionLoop/visualCaptcha/issues/9

The samples have some code to avoid the scrolling to top issue, but I'm open to better suggestions.

**Comment by yyuna** [comment]
@BrunoBernardino 
 Maybe you could use href="javascript:void(0)" instead of href="#" :D

**Comment by BrunoBernardino** [comment]
There are some [big discussions about that](http://stackoverflow.com/questions/134845/href-attribute-for-javascript-links-or-javascriptvoid0) and while my personal preference goes with `javascript:void(0);`, I've seen issues with accessibility-focused browsers with that vs `#`, and that's why I went with that.

In any case, you're free to change it for yourself! :)
